brittAnderson/psych363Practice

gitnames/yijing.txt

Please approve the pull request from Yijing Feng

adding yijing

---

gitnames/sean.txt

Adding a file to the psych363practice repo per the requirements of the [assignment](https://github.com/brittAnderson/Intro2Computing4Psychology/blob/master/assessments/githubPullRequestAssmnt.org)

Adding file to test version control - sean.txt

---

gitnames/Keagan.txt

Please add my .txt file to your repository.
Thanks!

Adding .txt file by Keagan

---

gitnames/isaac.txt

Please add my file to the repository.

adding isaac

---

Claire.txt

This is a pull request for my assignment.

adding Claire.txt

---

gitnames/Claire2.txt

This is for my pull request assignment.

Adding Claire2

---

gitnames/brittany.txt

This is the pull request assignment.

adding brittany

---

gitnames/sarah.txt
readme.org

request for adding Sarah name text file.

Updated Pull Request - Sarah Naseem 

---

olya.txt

My contribution to this repository.

adding gitname

---

gitnames/navi.txt
gitnames/navi2.txt

This is my pull request

---

gitnames/enes.txt

This is my pull request for Version Control and Pull Request Assignment

adding enes

---

gitnames/alex.txt

Adding Alex

---

gitnames/Inaara.txt

my first commit

---

gitnames/asmaK.txt

adding asmaK.txt

---

gitnames/sultan.txt

adding sultan

---

Yuanxi.txt

I alreay added my own txt file and hope i finished it correctly.
Yuanxi Liu

adding Yuanxi.txt

---

gitnames/wasam.txt
wasyedassign.txt

Version Control and Pull request assignment || 20746474

---

gitnames/Fantongzhang2.txt

adding Fantongzhang2

---

gitnames/danielZehr_20569314.txt

Here's my file!

---

gitnames/ArdenF.txt

I'm pulling to add my name text file!

adding Arden Fenton as text file

---

gitnames/isabelle.txt.
isabelle.txt.

Adding my file name (isabelle.txt.) to the gitnames file.

Assignment Pull Request 

---

gitnames/rachelWoima.txt

This is my pull request for the addition of my txt file

adding rachelWoima

---

umeira.txt

Hello Professor,
Please accept my pull request from my repository for my text file.

Pull Request

---

gitnames/abigail.txt

Please add my file  abigail.txt through this pull request.

adding abigail.txt

---

gitnames/francisHe.txt

francisHe.txt push

---

gitnames/sirui.txt

adding sirui

---

gitnames/jingwen.txt

Git Pull Request from Jingwen Min

---

Git_names/esosa.txt
README.md
gitnames/esosa.txt

Pull Request for the Spring 2022 gitnames assignment

Pull Request for gitnames

---

gitnames/Rowyn.txt

adding Rowyn

---

gitnames/yuhan.txt

practicing opening a pull request.

adding yuhan

---

gitnames/Alex.txt

I have added my Alex.txt for the version control assignment.
Thanks,
Alex

adding Alex.txt

---

j3rowlan.txt

adding Julia.txt

---

Wisam.txt

Trying to add the file to repository.

adding Wisam

---

gitnames/kiarash.txt

Adding my text file to the **gitnames** sub-directory. 
-- Kiarash (20848466)

Adding kiarash.txt to the bunch

---

gitnames/alina.txt

adding alina

---

gitnames/chel-b.txt

Push changes ( Adding txt file )

Creating a txt file under my name with a sentence.

---

gitnames/molly.txt

adding molly.txt

---

gitnames/matthew.txt

adding matthew.txt

---

gitnames/tongyuwang.txt

tongyuwang

---

gitnames/angelachen20909510.txt

adding angelachen20909510.txt

---

britt2.txt
gitnames/sonal.txt

Sonal Misra
Student ID: 20899104

adding sonal.txt file

---

gitnames/alexH.txt

adding alexH

---

gitnames/harish.txt

Creating pull request for Version Control 
hmylvaga
20785596

added file for PSYCH363

---

lauren.txt

adding my text file lauren

---

gitnames/simran.txt

Version Control and Pull Request Assignment

adding simran.txt

---

gitnames/Dasha.txt

adding Dasha - name file

---

gitnames/olive.txt

Olive Lin -> adding a file for PSYCH 363

adding olive

---

gitnames/aaron.txt

Working through the Version Control and Pull Request assignment

added aaron.txt
